name: 02 - Publish Page

env:
  access: public
  github-registry: https://npm.pkg.github.com
  github-token: ${{ secrets.GITHUB_TOKEN }}
  npmjs-registry: https://registry.npmjs.org
  scope: '@public-ui'

on:
  workflow_call:
  workflow_dispatch:

jobs:
  publish:
    if: github.repository == 'public-ui/kolibri'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false



      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: '${{env.npmjs-registry}}'
          scope: '${{env.scope}}'
      - uses: pnpm/action-setup@v4
        id: pnpm-install
        with:
          version: 9
      - id: pnpm-cache
        shell: bash
        run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store
          restore-keys: |
            ${{ runner.os }}-pnpm-store

      - name: Install
        run: pnpm i --no-frozen-lockfile --no-verify-store-integrity

      - name: Build
        run: pnpm -r build

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: '${{env.github-registry}}'
          scope: '${{env.scope}}'

      - name: Publish designer
        run: npm publish --access restricted || true
        working-directory: packages/designer
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish sample react
        run: npm publish --access restricted || true
        working-directory: packages/samples/react
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
